/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.time.LocalDate;
import java.time.LocalDateTime;
import Controlador.TicketControlador;
import Controlador.PartidoControlador;
import Modelo.PartidoModelo;
import java.awt.Image;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yorch
 */
public class MasPartidos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MasPartidos.class.getName());
      private final PartidoControlador controlador = new PartidoControlador();  
      DefaultTableModel modeloTabla = new DefaultTableModel(new Object[]{"ID","Local","Visitante","Fecha","Hora","Fase","Estadio","Ciudad","Capacidad"},0);
      private DefaultTableModel seleccionadosPrevios = new DefaultTableModel(
        new Object[]{"ID","Partido_ID","Local","Visitante","Fase","Estadio",
                     "Fecha","Hora","Asiento","Sección","Precio","Estado"},0
    );
      String id;
    private int partido_id;
    /**
     * Creates new form Venta
     */
    public MasPartidos() {
       initComponents();
         getContentPane().setBackground(new java.awt.Color(46, 125, 90));
         cargarPartidos();
         jtseleccion.setModel(modeloTabla);
         ImageIcon icono = new ImageIcon(getClass().getResource("/Img/WEARE26VERDE.png"));

    Image imagen = icono.getImage();

    Image escala = imagen.getScaledInstance(
            jLabel6.getWidth(),
            jLabel6.getHeight(),
            Image.SCALE_SMOOTH
    );

    jLabel6.setIcon(new ImageIcon(escala));
        
        
   
    boxequipo.removeAllItems();
    boxequipo.addItem("Guatemala");
    boxequipo.addItem("México");
    boxequipo.addItem("Argentina");
    boxequipo.addItem("Brasil");
    boxequipo.addItem("España");
    boxequipo.addItem("Francia");
    boxequipo.addItem("Alemania");
    boxequipo.addItem("Portugal");
    
    boxequipo.addActionListener(e -> {
        String seleccion = boxequipo.getSelectedItem().toString();
    cargarPartidosFiltrados(seleccion);
        });

     jtseleccion.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
      int fila = jtseleccion.getSelectedRow();
      if (fila >= 0) {

         
            }
        }
    });
    }
 public MasPartidos(DefaultTableModel seleccionadosPrevios) {
        initComponents();
        this.seleccionadosPrevios = seleccionadosPrevios;
        getContentPane().setBackground(new java.awt.Color(46, 125, 90));
        cargarPartidos();
        jtseleccion.setModel(modeloTabla);
         ImageIcon icono = new ImageIcon(getClass().getResource("/Img/WEARE26VERDE.png"));

    Image imagen = icono.getImage();

    Image escala = imagen.getScaledInstance(
            jLabel6.getWidth(),
            jLabel6.getHeight(),
            Image.SCALE_SMOOTH
    );

    jLabel6.setIcon(new ImageIcon(escala));
        boxequipo.removeAllItems();
    boxequipo.addItem("Guatemala");
    boxequipo.addItem("México");
    boxequipo.addItem("Argentina");
    boxequipo.addItem("Brasil");
    boxequipo.addItem("España");
    boxequipo.addItem("Francia");
    boxequipo.addItem("Alemania");
    boxequipo.addItem("Portugal");
    
    boxequipo.addActionListener(e -> {
        String seleccion = boxequipo.getSelectedItem().toString();
    cargarPartidosFiltrados(seleccion);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtseleccion = new javax.swing.JTable();
        btconfirmar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        boxequipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECCION DE PARTIDO");

        jtseleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtseleccion);

        btconfirmar.setBackground(new java.awt.Color(2, 153, 52));
        btconfirmar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btconfirmar.setForeground(new java.awt.Color(243, 236, 236));
        btconfirmar.setText("CONFIRMAR");
        btconfirmar.addActionListener(this::btconfirmarActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(2, 153, 52));
        btnBuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(243, 236, 236));
        btnBuscar.setText("MOSTRAR TODOS");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jButton2.setBackground(new java.awt.Color(232, 55, 55));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(243, 236, 236));
        jButton2.setText("ATRAS");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel6.setText("jLabel6");

        boxequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxequipo.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Equipos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addComponent(btconfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
   public void cargarPartidos(){
    modeloTabla.setRowCount(0);
    for(PartidoModelo p : controlador.obtenerPartido()){
        modeloTabla.addRow(new Object[]{
            p.getId(),
            p.getEquipo_local(),
            p.getEquipo_visitante(),
            p.getFecha(),
            p.getHora(),
            p.getFase(),
            p.getEstadio(),
            p.getCiudad(),
            p.getCapacidad()
        });
    }
}

public void cargarPartidosFiltrados(String seleccion){
    modeloTabla.setRowCount(0);
    for(PartidoModelo p : controlador.buscarPorSeleccion(seleccion)){
        modeloTabla.addRow(new Object[]{
            p.getId(),
            p.getEquipo_local(),
            p.getEquipo_visitante(),
            p.getFecha(),
            p.getHora(),
            p.getFase(),
            p.getEstadio(),
            p.getCiudad(),
            p.getCapacidad()
        });
    }
}
       
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        cargarPartidos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconfirmarActionPerformed
        // TODO add your handling code here:
        int fila = jtseleccion.getSelectedRow();
        if (fila >= 0) {
            int idPartido = Integer.parseInt(jtseleccion.getValueAt(fila, 0).toString());
            TICKETDETALLE v = new TICKETDETALLE(idPartido, seleccionadosPrevios);
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setExtendedState(javax.swing.JFrame.NORMAL);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un partido");
        }
    }//GEN-LAST:event_btconfirmarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TICKETDETALLE v = new TICKETDETALLE(partido_id, seleccionadosPrevios);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        v.setExtendedState(javax.swing.JFrame.NORMAL);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MasPartidos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxequipo;
    private javax.swing.JButton btconfirmar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtseleccion;
    // End of variables declaration//GEN-END:variables
}
