/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author 90NR0JE7M002D0
 */
public class MenuPrincipalAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName());

    /**
     * Creates new form MenuPrincipalAdmin
     */
    public MenuPrincipalAdmin() {
        initComponents(); 
          getContentPane().setBackground(new java.awt.Color(45, 70, 95));
    jMenuBar1.setBackground(new java.awt.Color(24, 95, 165));
    jMenuBar1.setOpaque(true);
    jmPartido.setForeground(java.awt.Color.WHITE);
    jmTicket.setForeground(java.awt.Color.WHITE);
    jmClientes.setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPartido = new javax.swing.JMenu();
        jmPartidos = new javax.swing.JMenuItem();
        jmTicket = new javax.swing.JMenu();
        jmCrearTicket = new javax.swing.JMenuItem();
        jmClientes = new javax.swing.JMenu();
        jmCrudClientes = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenu();
        jmUsuario = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("🏆 Sistema de Tickets Admin — Mundial 2026");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        jLabel1.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO AL SISTEMA DE TAQUILLA DEL MUNDIAL");

        jmPartido.setBackground(new java.awt.Color(255, 255, 255));
        jmPartido.setForeground(new java.awt.Color(255, 255, 255));
        jmPartido.setText("Crear Partido");

        jmPartidos.setText("Partidos");
        jmPartidos.addActionListener(this::jmPartidosActionPerformed);
        jmPartido.add(jmPartidos);

        jMenuBar1.add(jmPartido);

        jmTicket.setBackground(new java.awt.Color(255, 255, 255));
        jmTicket.setText("Crear Ticket");

        jmCrearTicket.setText("Ticket");
        jmCrearTicket.addActionListener(this::jmCrearTicketActionPerformed);
        jmTicket.add(jmCrearTicket);

        jMenuBar1.add(jmTicket);

        jmClientes.setBackground(new java.awt.Color(255, 255, 255));
        jmClientes.setForeground(new java.awt.Color(255, 255, 255));
        jmClientes.setText("Crud CIientes");

        jmCrudClientes.setText("Clientes");
        jmCrudClientes.addActionListener(this::jmCrudClientesActionPerformed);
        jmClientes.add(jmCrudClientes);

        jMenuBar1.add(jmClientes);

        jmUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jmUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jmUsuarios.setText("Crud Usuarios");

        jmUsuario.setText("Usuarios");
        jmUsuario.addActionListener(this::jmUsuarioActionPerformed);
        jmUsuarios.add(jmUsuario);

        jMenuBar1.add(jmUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnVolver)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPartidosActionPerformed
        PartidoVista par = new PartidoVista(); 
        par.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmPartidosActionPerformed

    private void jmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioActionPerformed
        UsuarioVista usuario = new UsuarioVista(); 
        usuario.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_jmUsuarioActionPerformed

    private void jmCrearTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearTicketActionPerformed
        TicketVista tic = new TicketVista();
        tic.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmCrearTicketActionPerformed

    private void jmCrudClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrudClientesActionPerformed
        ClienteCrud cliente = new ClienteCrud(); 
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmCrudClientesActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        LoginSoporte login = new LoginSoporte();
        login.setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
try {
    javax.swing.UIManager.setLookAndFeel(
        javax.swing.UIManager.getCrossPlatformLookAndFeelClassName()
    );
} catch (Exception ex) {
    logger.log(java.util.logging.Level.SEVERE, null, ex);
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenuItem jmCrearTicket;
    private javax.swing.JMenuItem jmCrudClientes;
    private javax.swing.JMenu jmPartido;
    private javax.swing.JMenuItem jmPartidos;
    private javax.swing.JMenu jmTicket;
    private javax.swing.JMenuItem jmUsuario;
    private javax.swing.JMenu jmUsuarios;
    // End of variables declaration//GEN-END:variables
}
