/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.PartidoModelo;
import Controlador.PartidoControlador;
import java.time.LocalDate;
import java.util.Date;
import java.time.ZoneId;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.InputStream;
import javax.swing.ImageIcon;
/**
 *
 * @author DIEGO JUAREZ
 */
public class PartidoVista extends javax.swing.JFrame {
    private final PartidoControlador controlador = new PartidoControlador();
    
 DefaultTableModel modeloTabla = new DefaultTableModel(new Object[]{"Id", "Local", "Visitante", "Fecha", "Hora", "Fase", "Estadio", "Ciudad", "Capacidad", "Estado"},0);
 String id;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PartidoVista.class.getName());

    /**
     * Creates new form PartidoVista
     */
    public PartidoVista() {
        initComponents();
        setLocationRelativeTo(null);
                 getContentPane().setBackground(new java.awt.Color(45, 70, 95));
         cargarEquipos();
         fasePartido();
         jtPartido.setModel(modeloTabla);
    ImageIcon icono = new ImageIcon(getClass().getResource("/Img/WEARE26AZUL.jpg"));
    Image imagen = icono.getImage();
    Image escala = imagen.getScaledInstance(
            jLabel11.getWidth(),
            jLabel11.getHeight(),
            Image.SCALE_SMOOTH
    );

    jLabel11.setIcon(new ImageIcon(escala));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcLocal = new javax.swing.JComboBox<>();
        jcFase = new javax.swing.JComboBox<>();
        txtCapacidad = new javax.swing.JTextField();
        jcVisitante = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPartido = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEstadio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Partidos");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ciudad:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capacidad:");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fase del partido:");

        jcLocal.addActionListener(this::jcLocalActionPerformed);

        txtCapacidad.addActionListener(this::txtCapacidadActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(23, 116, 209));
        btnGuardar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(243, 236, 236));
        btnGuardar.setText("Registrar Partido");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Equipo Local");

        btnBuscar.setBackground(new java.awt.Color(23, 116, 209));
        btnBuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(243, 236, 236));
        btnBuscar.setText("Buscar Partido");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jtPartido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPartidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPartido);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Equipo Visitante");

        btnActualizar.setBackground(new java.awt.Color(23, 116, 209));
        btnActualizar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(243, 236, 236));
        btnActualizar.setText("Modificar Partido");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(232, 55, 55));
        btnEliminar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(243, 236, 236));
        btnEliminar.setText("Cambiar Estado");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha del Partido:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora:");

        txtCiudad.addActionListener(this::txtCiudadActionPerformed);

        jLabel6.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estadio:");

        txtEstadio.addActionListener(this::txtEstadioActionPerformed);

        jLabel11.setText("jLabel11");

        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 12)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(128, 128, 128))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jcLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jcVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jcFase, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(14, 14, 14))
                                                    .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(35, 35, 35)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void fasePartido(){
        String[] fases = {
            "Fase de grupos - J1",
            "Fase de grupos - J2",
            "Fase de grupos - J3",
            "Octavos de Final",
            "Cuartos de Final",
            "Semifinales",
            "Final"
        };
        for(String fase : fases){
            jcFase.addItem(fase);

        }
    }
    private void cargarEquipos() {
        String[] equipos = {
            "Guatemala",
            "México",
            "Argentina",
            "Brasil",
            "España",
            "Francia",
            "Alemania",
            "Portugal"
        };

        for(String equipo : equipos){
            jcLocal.addItem(equipo);
            jcVisitante.addItem(equipo);
        }
    }
    public void cargarPartidos(){
          modeloTabla.setRowCount(0);
        for(PartidoModelo Partido : controlador.obtenerPartido()){
            modeloTabla.addRow(new Object[]{Partido.getId(), Partido.getEquipo_local(), Partido.getEquipo_visitante(), Partido.getFecha(),Partido.getHora() ,Partido.getFase(),Partido.getEstadio(),Partido.getCiudad(),Partido.getCapacidad()});
        }
    }
    public void cargarPartidosFiltrados(String seleccion){

    modeloTabla.setRowCount(0);

    for(PartidoModelo partido : controlador.buscarPorSeleccion(seleccion)){

        modeloTabla.addRow(new Object[]{
            partido.getId(),
            partido.getEquipo_local(),
            partido.getEquipo_visitante(),
            partido.getFecha(),
            partido.getHora(),
            partido.getFase(),
            partido.getEstadio(),
            partido.getCiudad(),
            partido.getCapacidad()
        });
    }
}
    private void jcLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcLocalActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String local = jcLocal.getSelectedItem().toString();
        String visitante = jcVisitante.getSelectedItem().toString();
        String fase = jcFase.getSelectedItem().toString();

        if(local.equalsIgnoreCase(visitante)){

            JOptionPane.showMessageDialog(
                this,
                "El equipo local y el equipo visitante no puede ser el mismo"
            );
            return;
        }
        Date fechaPartido = jDate.getDate();
        LocalDate fecha = fechaPartido.toInstant()
        .atZone(ZoneId.systemDefault())
        .toLocalDate();
        controlador.crearPartido(local,visitante, fecha, txtHora.getText(), fase, txtEstadio.getText(), txtCiudad.getText(), Integer.parseInt(txtCapacidad.getText()) );
        cargarPartidos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String[] opciones = {
            "Mostrar todos",
            "Buscar por equipo"
        };

        int opcion = JOptionPane.showOptionDialog(
            this,
            "¿Qué deseas hacer?",
            "Buscar Partidos",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if(opcion == 0){
            cargarPartidos();
        }

        else if(opcion == 1){

            String seleccion = JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre de la selección:"
            );

            if(seleccion != null && !seleccion.trim().isEmpty()){
                cargarPartidosFiltrados(seleccion);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jtPartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPartidoMouseClicked
        // TODO add your handling code here:

        int fila = jtPartido.getSelectedRow();

        if(fila != -1){

            id = jtPartido.getValueAt(fila, 0).toString();

            jcLocal.setSelectedItem(
                jtPartido.getValueAt(fila, 1).toString()
            );

            jcVisitante.setSelectedItem(
                jtPartido.getValueAt(fila, 2).toString()
            );

            try{
                 LocalDate fecha = (LocalDate)
                 jtPartido.getValueAt(fila, 3);
                 Date fechaDate = java.sql.Date.valueOf(fecha);
                 jDate.setDate(fechaDate);

            }catch(Exception e){
                e.printStackTrace();
            }

            txtHora.setText(
                jtPartido.getValueAt(fila, 4).toString()
            );

            jcFase.setSelectedItem(
                jtPartido.getValueAt(fila, 5).toString()
            );

            txtEstadio.setText(
                jtPartido.getValueAt(fila, 6).toString()
            );

            txtCiudad.setText(
                jtPartido.getValueAt(fila, 7).toString()
            );

            txtCapacidad.setText(
                jtPartido.getValueAt(fila, 8).toString()
            );
        }
    }//GEN-LAST:event_jtPartidoMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String local = jcLocal.getSelectedItem().toString();
        String visitante = jcVisitante.getSelectedItem().toString();
        String fase = jcFase.getSelectedItem().toString();

        if(local.equalsIgnoreCase(visitante)){

            JOptionPane.showMessageDialog(
                this,
                "El equipo local y el equipo visitante no puede ser el mismo"
            );
            return;
        }
        Date fechaPartido = jDate.getDate();
        LocalDate fecha = fechaPartido.toInstant()
        .atZone(ZoneId.systemDefault())
        .toLocalDate();
        controlador.modificarPartido(Integer.parseInt(id), local,visitante, fecha, txtHora.getText(), fase, txtEstadio.getText(), txtCiudad.getText(), Integer.parseInt(txtCapacidad.getText()) );
        cargarPartidos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = jtPartido.getSelectedRow();

        if(fila == -1){

            JOptionPane.showMessageDialog(
                this,
                "Seleccione un partido"
            );

            return;
        }

        int id = Integer.parseInt(
            jtPartido.getValueAt(fila, 0).toString()
        );

        String[] opciones = {
            "DISPONIBLE",
            "FINALIZADO",
            "CANCELADO"
        };

        String estado = (String) JOptionPane.showInputDialog(
            this,
            "Seleccione el nuevo estado:",
            "Cambiar Estado",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if(estado != null){

            controlador.cambiarPartido(id, estado);

            cargarPartidos();

            JOptionPane.showMessageDialog(
                this,
                "Estado actualizado correctamente"
            );
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void txtEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MenuPrincipalAdmin menu = new MenuPrincipalAdmin();
         menu.setVisible(true); 
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PartidoVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcFase;
    private javax.swing.JComboBox<String> jcLocal;
    private javax.swing.JComboBox<String> jcVisitante;
    private javax.swing.JTable jtPartido;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtEstadio;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
