/*                                                 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelo.TicketPartidoDTO;
import Controlador.TicketControlador;
import Controlador.PartidoControlador;
import Modelo.PartidoModelo;
import java.awt.Image;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
/**
 *
 * @author yorch 
 */
public class TicketVista extends javax.swing.JFrame {
    TicketControlador controlador = new TicketControlador();
    DefaultTableModel modelotabla=new DefaultTableModel(new Object[]{"ID","Partido_ID","Local","Visitante","Fase","Estadio",
     "fecha_partido","hora_partido","numero_asiento","seccion","precio","estado"},0);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicketVista.class.getName());

    /**
     * Creates new form Ticket
     */
    public TicketVista() {
        initComponents();
        JTtickets.setModel(modelotabla);  
        txtid.setEditable(false);
        txtpartido.setEditable(false);
        txtlocal.setEditable(false);
        txtvisita.setEditable(false);
        txtfase.setEditable(false);
        txtfecha.setEditable(false);
        txthora.setEditable(false);
        txtestadio.setEditable(false);
        
        
        cargarTickets();
        cargarPartidos();
        
        
       boxestado.removeAllItems();
       boxestado.addItem("DISPONIBLE");
       boxestado.addItem("RESERVADO");
       boxestado.addItem("VENDIDO");
         
        
       boxestado.addActionListener(e -> {
       Object seleccionadoObj = boxestado.getSelectedItem();
       if (seleccionadoObj != null) {
       String seleccionado = seleccionadoObj.toString();
       if (!seleccionado.equals("DISPONIBLE") && txtid.getText().isEmpty()) {
       JOptionPane.showMessageDialog(this,"El ticket nuevo será creado como DISPONIBLE automáticamente");
       boxestado.setSelectedItem("DISPONIBLE");
         }
           }
          });
      
        boxseccion.removeAllItems();
        boxseccion.addItem("GENERAL");
        boxseccion.addItem("TRIBUNA");
        boxseccion.addItem("PREFERENCIAL");
        boxseccion.addItem("VIP");
        getContentPane().setBackground(new java.awt.Color(45, 70, 95));
          ImageIcon icono = new ImageIcon(getClass().getResource("/Img/WEARE26AZUL.jpg"));
    Image imagen = icono.getImage();
    Image escala = imagen.getScaledInstance(
            jLabel16.getWidth(),
            jLabel16.getHeight(),
            Image.SCALE_SMOOTH
    );

    jLabel16.setIcon(new ImageIcon(escala));

        
        
      JTtickets.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
        int fila = JTtickets.getSelectedRow();
        if (fila != -1) {
        int idTicket = Integer.parseInt(modelotabla.getValueAt(fila, 0).toString());
        if (JOptionPane.showConfirmDialog(TicketVista.this, "¿Deseas eliminar este ticket?") == JOptionPane.YES_OPTION) {
        controlador.eliminar(idTicket);
        cargarTickets();
        JOptionPane.showMessageDialog(TicketVista.this, "Ticket eliminado correctamente");
         }
         }
         }
         }
        });

        
        JTtickets.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        JTticketsMouseClicked(evt);
        }
    });
        
        txtid.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        JOptionPane.showMessageDialog(TicketVista.this,"El ID se generara solo, Porfavor siga con el proceso.");
         }
       });

        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
        };
        }
    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTtickets = new javax.swing.JTable();
        btcrear = new javax.swing.JButton();
        btactualizar = new javax.swing.JButton();
        btcambiarestado = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        boxseccion = new javax.swing.JComboBox<>();
        txtprecio = new javax.swing.JTextField();
        txtasiento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btbuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtpartido = new javax.swing.JTextField();
        xt5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtlocal = new javax.swing.JTextField();
        txtvisita = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        txthora = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtfase = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        stadio = new javax.swing.JLabel();
        txtestadio = new javax.swing.JTextField();
        boxestado = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Tickets");

        jLabel2.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Asiento");

        jLabel4.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seccion");

        jLabel5.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio");

        jLabel7.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PARTIDO");

        JTtickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTtickets);

        btcrear.setBackground(new java.awt.Color(23, 116, 209));
        btcrear.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btcrear.setForeground(new java.awt.Color(243, 236, 236));
        btcrear.setText("CREAR TICKET");
        btcrear.addActionListener(this::btcrearActionPerformed);

        btactualizar.setBackground(new java.awt.Color(23, 116, 209));
        btactualizar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btactualizar.setForeground(new java.awt.Color(243, 236, 236));
        btactualizar.setText("ACTUALIZAR TICKET");
        btactualizar.addActionListener(this::btactualizarActionPerformed);

        btcambiarestado.setBackground(new java.awt.Color(23, 116, 209));
        btcambiarestado.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btcambiarestado.setForeground(new java.awt.Color(243, 236, 236));
        btcambiarestado.setText("CAMBIAR ESTADO");
        btcambiarestado.addActionListener(this::btcambiarestadoActionPerformed);

        bteliminar.setBackground(new java.awt.Color(232, 55, 55));
        bteliminar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(243, 236, 236));
        bteliminar.setText("ELIMINAR ");
        bteliminar.addActionListener(this::bteliminarActionPerformed);

        boxseccion.setBackground(new java.awt.Color(255, 255, 255));
        boxseccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtprecio.addActionListener(this::txtprecioActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnBuscar.setBackground(new java.awt.Color(23, 116, 209));
        btnBuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(243, 236, 236));
        btnBuscar.setText("BUSCAR PARTIDO");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btbuscar.setBackground(new java.awt.Color(23, 116, 209));
        btbuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        btbuscar.setForeground(new java.awt.Color(243, 236, 236));
        btbuscar.setText("BUSCAR TICKET");
        btbuscar.addActionListener(this::btbuscarActionPerformed);

        jLabel3.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estado");

        xt5.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        xt5.setForeground(new java.awt.Color(255, 255, 255));
        xt5.setText("Local");

        jLabel6.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Visita");

        jLabel8.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha");

        jLabel9.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hora");

        txtfecha.addActionListener(this::txtfechaActionPerformed);

        jLabel10.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DETALLES DE TICKET");

        jLabel11.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DETALLES PARTIDO");

        jLabel12.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fase");

        jLabel13.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PARTIDOS");

        jLabel14.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TICKETS");

        jLabel15.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID");

        stadio.setFont(new java.awt.Font("FWC2026 UltraCondensed Medium", 0, 20)); // NOI18N
        stadio.setForeground(new java.awt.Color(255, 255, 255));
        stadio.setText("Estadio");

        boxestado.setBackground(new java.awt.Color(255, 255, 255));
        boxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("jLabel11");

        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 12)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addGap(325, 325, 325)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(xt5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stadio))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtpartido)
                                            .addComponent(txtlocal)
                                            .addComponent(txtvisita)
                                            .addComponent(txtfecha)
                                            .addComponent(txthora)
                                            .addComponent(txtfase)
                                            .addComponent(txtestadio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel11)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addComponent(jLabel10)
                                        .addGap(96, 96, 96))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel15))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(boxseccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtprecio)
                                                    .addComponent(txtasiento)
                                                    .addComponent(boxestado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(44, 44, 44)))
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btcambiarestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bteliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btcrear, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxseccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtasiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(boxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtpartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xt5)
                            .addComponent(txtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtvisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtfase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stadio)
                            .addComponent(txtestadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btcrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btcambiarestado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bteliminar)))
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcrearActionPerformed
    int partido_id = Integer.parseInt(txtpartido.getText());
    String seccion = boxseccion.getSelectedItem().toString();
    String numero_asiento = txtasiento.getText();
    double precio = Double.parseDouble(txtprecio.getText());
    String estado = "DISPONIBLE";
    
    PartidoControlador pc = new PartidoControlador();
    boolean existe = pc.obtenerPartido().stream()
    .anyMatch(p -> p.getId() == partido_id);
    
    if (txtfecha.getText() == null || txtfecha.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un partido para obtener la fecha");
        return;
    }
LocalDate fechaPartido;
try {
    fechaPartido = LocalDate.parse(txtfecha.getText().trim());
} catch (Exception e) {
    JOptionPane.showMessageDialog(this,
        "Formato de fecha inválido: " + txtfecha.getText());
    return;
}
   boolean resultado = controlador.crearTicket(
    partido_id,
    numero_asiento,
    seccion,
    precio,
    estado,
    fechaPartido.atStartOfDay()
);
    if (resultado) {
        JOptionPane.showMessageDialog(this, "Ingresado correctamente");
    } else {
        JOptionPane.showMessageDialog(this, "No se ingresó correctamente");
    }
    cargarTickets();
   
    }//GEN-LAST:event_btcrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String[] opciones = {
            "Mostrar todos",
            "Buscar por equipo"
        };
        int opcion = JOptionPane.showOptionDialog(
            this,
            "¿Qué deseas hacer?",
            "Buscar Partidos",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );
        if(opcion == 0){
            cargarPartidos();
        }
        else if(opcion == 1){
            String seleccion = JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre de la selección:"
            );
            if(seleccion != null && !seleccion.trim().isEmpty()){
                cargarPartidosFiltrados(seleccion);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarActionPerformed
if (txtid.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un ticket primero");
        return;
    }

    int idTicket = Integer.parseInt(txtid.getText());
    int partido_id = Integer.parseInt(txtpartido.getText());

    LocalDate fecha = LocalDate.parse(txtfecha.getText());

boolean resultado = controlador.actualizarTicket(
    idTicket,
    partido_id,
    fecha.atStartOfDay(),
    txtasiento.getText(),
    boxseccion.getSelectedItem().toString(),
    Double.parseDouble(txtprecio.getText()),
    boxestado.getSelectedItem().toString()
);

    if(resultado){
        JOptionPane.showMessageDialog(this,"Ticket actualizado correctamente");
        cargarTickets();
    }else{
        JOptionPane.showMessageDialog(this,"Error al actualizar el ticket");
    }



    }//GEN-LAST:event_btactualizarActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void btcambiarestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcambiarestadoActionPerformed
        // TODO add your handling code here:
  if (txtid.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un ticket primero");
        return;
    }
    int fila = JTtickets.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un ticket en la tabla");
        return;
    }
    int idTicket = Integer.parseInt(txtid.getText());
    String nuevoEstado = boxestado.getSelectedItem().toString();
    String estadoActual = modelotabla.getValueAt(fila, 11).toString();

    if (nuevoEstado.equals(estadoActual)) {
    JOptionPane.showMessageDialog(this, "Debes seleccionar un estado diferente al actual");
     return;
    }
    boolean resultado = controlador.cambiarEstado(idTicket, nuevoEstado);
    if (resultado) {
        JOptionPane.showMessageDialog(this, "Estado actualizado correctamente");
        cargarTickets();
    } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar el estado");
    }
      
    }//GEN-LAST:event_btcambiarestadoActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        // TODO add your handling code here:
          int fila = JTtickets.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un ticket en la tabla");
        return;
    }

    int idTicket = Integer.parseInt(modelotabla.getValueAt(fila, 0).toString());

    if (JOptionPane.showConfirmDialog(this, "¿Deseas eliminar este ticket?") == JOptionPane.YES_OPTION) {
        controlador.eliminar(idTicket);
        cargarTickets();
        JOptionPane.showMessageDialog(this, "Ticket eliminado correctamente");
    }   
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
        // TODO add your handling code here:
        String[] opciones = {"Mostrar todos", "Buscar por equipo"};
    int opcion = JOptionPane.showOptionDialog(
        this,
        "¿Qué deseas hacer?",
        "Buscar Tickets",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.INFORMATION_MESSAGE,
        null,
        opciones,
        opciones[0]
    );

    if(opcion == 0){
        cargarTickets();
    } else if(opcion == 1){
        String seleccion = JOptionPane.showInputDialog(this, "Ingrese el nombre de la selección:");
        if(seleccion != null && !seleccion.trim().isEmpty()){
            modelotabla.setRowCount(0);
            for (TicketPartidoDTO t : controlador.buscarPorSeleccion(seleccion)) {
                modelotabla.addRow(new Object[]{
                    t.getTicketId(),
                    t.getPartidoId(),
                    t.getEquipoLocal(),
                    t.getEquipoVisitante(),
                    t.getFase(),
                    t.getEstadio(),
                    t.getFecha(),
                    t.getHora(),
                    t.getNumeroAsiento(),
                    t.getSeccion(),
                    t.getPrecio(),
                    t.getEstado()
                });
            }
        }
    }
    }//GEN-LAST:event_btbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrincipalAdmin menu = new MenuPrincipalAdmin();
        menu.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed
private void cargarTickets() {
    modelotabla.setRowCount(0);
    for (TicketPartidoDTO dto : controlador.obtenerTicketsConPartido()) {
        modelotabla.addRow(new Object[]{
            dto.getTicketId(),    
            dto.getPartidoId(),    
            dto.getEquipoLocal(),    
            dto.getEquipoVisitante(), 
            dto.getFase(),
            dto.getEstadio(),       
            dto.getFecha(),          
            dto.getHora(),            
            dto.getNumeroAsiento(),   
            dto.getSeccion(),        
            dto.getPrecio(),         
            dto.getEstado()         
        });
    }
}

private void cargarPartidos() {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"ID","Local","Visitante","Fecha","Hora","Fase","Estadio","Ciudad","Capacidad","Estado"}, 0
    );
    jTable1.setModel(modelo);

    PartidoControlador pc = new PartidoControlador();
    for (PartidoModelo p : pc.obtenerPartido()) {
    modelo.addRow(new Object[]{
        p.getId(),
        p.getEquipo_local(),
        p.getEquipo_visitante(),
        p.getFecha(),
        p.getHora(),
        p.getFase(),
        p.getEstadio(),
        p.getCiudad(),
        p.getCapacidad(),
        p.getEstado()
    });
    }
}
private void cargarPartidosFiltrados(String seleccion) {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"ID","Local","Visitante","Fecha","Hora","Fase","Estadio","Ciudad","Capacidad","Estado"}, 0
    );
    jTable1.setModel(modelo);

    PartidoControlador pc = new PartidoControlador();
    for (PartidoModelo p : pc.buscarPorSeleccion(seleccion)) {
        modelo.addRow(new Object[]{
            p.getId(),
            p.getEquipo_local(),
            p.getEquipo_visitante(),
            p.getFecha(),
            p.getHora(),
            p.getFase(),
            p.getEstadio(),
            p.getCiudad(),
            p.getCapacidad(),
            p.getEstado()
        });
    }
}
private void JTticketsMouseClicked(java.awt.event.MouseEvent evt) {
    int fila = JTtickets.getSelectedRow();
    if (fila != -1) {
       txtid.setText(modelotabla.getValueAt(fila,0).toString());   
       txtpartido.setText(modelotabla.getValueAt(fila,1).toString());  
       txtlocal.setText(modelotabla.getValueAt(fila,2).toString());   
       txtvisita.setText(modelotabla.getValueAt(fila,3).toString());  
       txtfase.setText(modelotabla.getValueAt(fila,4).toString());    
       txtestadio.setText(modelotabla.getValueAt(fila,5).toString());
       txtfecha.setText(modelotabla.getValueAt(fila,6).toString().split("T")[0]); 
       txthora.setText(modelotabla.getValueAt(fila,7).toString());   
       txtasiento.setText(modelotabla.getValueAt(fila,8).toString()); 
       boxseccion.setSelectedItem(modelotabla.getValueAt(fila,9).toString()); 
       txtprecio.setText(modelotabla.getValueAt(fila,10).toString()); 
       boxestado.setSelectedItem(modelotabla.getValueAt(fila,11).toString());
    }
}

    
private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
    int fila = jTable1.getSelectedRow();
    if (fila != -1) {
        txtid.setText("");
        txtasiento.setText("");
        txtprecio.setText("");
        boxestado.setSelectedIndex(-1); 
        boxseccion.setSelectedIndex(-1);
        
        String idPartido = jTable1.getValueAt(fila, 0).toString();  
        String local = jTable1.getValueAt(fila, 1).toString();
        String visitante = jTable1.getValueAt(fila, 2).toString();
        String fecha = jTable1.getValueAt(fila, 3).toString().split("T")[0];
        String hora = jTable1.getValueAt(fila, 4).toString();
        String fase = jTable1.getValueAt(fila, 5).toString();
        String estadio = jTable1.getValueAt(fila, 6).toString();
        
        txtpartido.setText(idPartido);
        txtlocal.setText(local);
        txtvisita.setText(visitante);
        txtfase.setText(fase);
        txtfecha.setText(fecha);
        txthora.setText(hora); 
       txtestadio.setText(estadio   );
    }
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TicketVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTtickets;
    private javax.swing.JComboBox<String> boxestado;
    private javax.swing.JComboBox<String> boxseccion;
    private javax.swing.JButton btactualizar;
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btcambiarestado;
    private javax.swing.JButton btcrear;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel stadio;
    private javax.swing.JTextField txtasiento;
    private javax.swing.JTextField txtestadio;
    private javax.swing.JTextField txtfase;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlocal;
    private javax.swing.JTextField txtpartido;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtvisita;
    private javax.swing.JLabel xt5;
    // End of variables declaration//GEN-END:variables

}